import 'package:flutter/material.dart';

import '../api/api_client.dart';
import '../api/models.dart';
import '../widgets/answer_text.dart';
import '../widgets/common.dart';
import '../widgets/source_card.dart';

const exampleQuestions = [
  'Within how many hours must a controller notify a personal data breach?',
  'What must an Indian app do before processing personal data of children?',
  'What is the maximum penalty under the DPDP Act for failing to protect personal data?',
  'Can a bank reject my loan application purely through an algorithm without any human involvement?',
];

class AskScreen extends StatefulWidget {
  const AskScreen({super.key, required this.api, this.initialQuestion, this.initialMode});

  final LegalRagApi api;

  /// Asked automatically on first build (from a shared link).
  final String? initialQuestion;
  final RetrievalMode? initialMode;

  @override
  State<AskScreen> createState() => _AskScreenState();
}

class _AskScreenState extends State<AskScreen> {
  final _controller = TextEditingController();
  final _sourceKeys = <int, GlobalKey>{};
  late RetrievalMode _mode = widget.initialMode ?? RetrievalMode.hybridRerank;
  AskResult? _result;
  String? _error;
  bool _loading = false;
  int? _highlighted;

  @override
  void initState() {
    super.initState();
    final question = widget.initialQuestion;
    if (question != null) WidgetsBinding.instance.addPostFrameCallback((_) => _ask(question));
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _ask([String? preset]) async {
    if (preset != null) _controller.text = preset;
    final question = _controller.text.trim();
    if (question.length < 2 || _loading) return;
    setState(() {
      _loading = true;
      _error = null;
      _highlighted = null;
    });
    try {
      final result = await widget.api.ask(question, _mode);
      setState(() {
        _result = result;
        _sourceKeys
          ..clear()
          ..addEntries(result.sources.map((s) => MapEntry(s.marker, GlobalKey())));
      });
    } on ApiException catch (e) {
      setState(() => _error = e.message);
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  void _showSource(int marker) {
    setState(() => _highlighted = marker);
    final context = _sourceKeys[marker]?.currentContext;
    if (context != null) {
      Scrollable.ensureVisible(context, duration: const Duration(milliseconds: 350), alignment: 0.1);
    }
  }

  @override
  Widget build(BuildContext context) {
    final wide = MediaQuery.sizeOf(context).width >= 1100;
    final result = _result;
    return PageFrame(
      title: 'Ask the law',
      subtitle: 'Answers grounded in the GDPR and India\'s DPDP Act 2023, generated by a local LLM with citations.',
      children: [
        _QuestionBox(controller: _controller, loading: _loading, onSubmit: _ask),
        const SizedBox(height: 12),
        Wrap(
          crossAxisAlignment: WrapCrossAlignment.center,
          spacing: 12,
          runSpacing: 8,
          children: [
            ModeSelector(value: _mode, enabled: !_loading, onChanged: (m) => setState(() => _mode = m)),
            Text(_mode.description, style: Theme.of(context).textTheme.bodySmall),
          ],
        ),
        const SizedBox(height: 16),
        if (_loading) ...[
          const LinearProgressIndicator(),
          const SizedBox(height: 8),
          const Text('Retrieving sources and generating the answer locally. On a CPU this can take 20–60 s.'),
          const SizedBox(height: 16),
        ],
        if (_error != null) ...[ErrorBanner(message: _error!, onRetry: _ask), const SizedBox(height: 16)],
        if (result == null && !_loading)
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: [for (final q in exampleQuestions) ActionChip(label: Text(q), onPressed: () => _ask(q))],
          ),
        if (result != null) wide ? _wideLayout(result) : _narrowLayout(result),
      ],
    );
  }

  Widget _answerCard(AskResult result) {
    final theme = Theme.of(context);
    final timings = result.timingsMs;
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(
                  result.abstained ? Icons.help_outline : Icons.check_circle_outline,
                  color: theme.colorScheme.primary,
                ),
                const SizedBox(width: 8),
                Text(result.abstained ? 'No answer in the sources' : 'Answer', style: theme.textTheme.titleMedium),
              ],
            ),
            const SizedBox(height: 12),
            AnswerText(
              answer: result.answer,
              onCitationTap: _showSource,
              validMarkers: result.sources.map((s) => s.marker).toSet(),
            ),
            const SizedBox(height: 16),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                Chip(avatar: const Icon(Icons.memory, size: 16), label: Text(result.model)),
                Chip(avatar: const Icon(Icons.manage_search, size: 16), label: Text(result.mode.label)),
                Chip(
                  avatar: const Icon(Icons.timer_outlined, size: 16),
                  label: Text(
                    'retrieval ${formatMs(timings['retrieval_total'])} · '
                    'generation ${formatMs(timings['generation'])}',
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _sourcesList(AskResult result) => Column(
    crossAxisAlignment: CrossAxisAlignment.stretch,
    children: [
      Text('Sources (${result.sources.length})', style: Theme.of(context).textTheme.titleMedium),
      const SizedBox(height: 8),
      for (final source in result.sources) ...[
        SourceCard(
          key: _sourceKeys[source.marker],
          source: source,
          cited: result.citedMarkers.contains(source.marker),
          highlighted: _highlighted == source.marker,
        ),
        const SizedBox(height: 8),
      ],
    ],
  );

  Widget _wideLayout(AskResult result) => Row(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      Expanded(flex: 5, child: _answerCard(result)),
      const SizedBox(width: 24),
      Expanded(flex: 4, child: _sourcesList(result)),
    ],
  );

  Widget _narrowLayout(AskResult result) => Column(
    crossAxisAlignment: CrossAxisAlignment.stretch,
    children: [_answerCard(result), const SizedBox(height: 24), _sourcesList(result)],
  );
}

class _QuestionBox extends StatelessWidget {
  const _QuestionBox({required this.controller, required this.loading, required this.onSubmit});

  final TextEditingController controller;
  final bool loading;
  final Future<void> Function([String?]) onSubmit;

  @override
  Widget build(BuildContext context) => TextField(
    controller: controller,
    enabled: !loading,
    minLines: 1,
    maxLines: 4,
    textInputAction: TextInputAction.search,
    onSubmitted: (_) => onSubmit(),
    decoration: InputDecoration(
      hintText: 'e.g. When must a company tell users about a data breach?',
      border: const OutlineInputBorder(),
      suffixIcon: IconButton(
        tooltip: 'Ask',
        icon: const Icon(Icons.send),
        onPressed: loading ? null : () => onSubmit(),
      ),
    ),
  );
}
